hiddewie/OpenRailwayMap-vector

import/openrailwaymap.lua
Fixes #28
Rotterdam Blaak is now duplicated properly as 2 stations.
=> Duplicate stations if multi-tagged

.github/workflows/deploy.yml, SETUP.md, api/Dockerfile, api/api.py, api/prepare-api.sh
Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/27
Documentation and script for easy local setup of API
=> API import scripts

import/Dockerfile, import/openrailwaymap.lua, import/sql/signals_with_azimuth.sql, import/sql/tile_views.sql
This will speed up the tile generation for the `signals` layer.
Later optimizations: add a single `feature` column in the materialized view, and a type to indicate signal, speed or electricity.
=> Add signal features to materialized view

import/openrailwaymap.lua
=> Strip `mi:` prefix from position values

.dockerignore, .github/workflows/deploy.yml, import/docker-startup.sh, proxy.Dockerfile, proxy/js/ui.js, proxy/proxy.conf.template
Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/99
Local import: data is imported using Docker compose, and the import script will output the imported data bounds as JSON. The proxy can pick up this file, and serve it for the UI.
Deployed: the file is manually written with the deployed import bounds.
Failure: if no file can be found, or the file fails to be served with a 200 OK response, the UI shows the entire map without bounds. 
I tried getting the bounds from https://maplibre.org/martin/sources-pg-tables.html, but these were not served by Martin, neither from a database nor from mbtlies tile files.
Import bounds not available: entire map is visible
Import bounds available and coordinates outside bound: UI moves the view inside the imported bounds.
Import bounds …
=> Replace hardcoded bounds to the imported region

proxy/css/ui.css, proxy/index.html, proxy/js/styles.mjs, proxy/js/ui.js
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/66
For raster tiles, adding a single extra layer is trivial. However, for vector background maps, an entire new MapLibre GL JS map instance must be made, to support a style, fonts, layers and sources.
The background map instance is created and rendered behind the railway map. Whenever the map changes location or zoom, the background map must also change.
This introduces a small lag. Possibly the raster implementation stays the same, while the vector implementation uses this implementation (?). 
The current opacity and saturation configuration options can be supported by plain CSS `filter` values for the entire background map.
Inspiration from https://github.com/maplibre/maplibre-gl-compare
=> Create background map visualization for rendering vector background map

import/sql/tile_views.sql, martin/configuration.yml, proxy/js/styles.mjs
This solves some of the clutter on the map, now that railway positions are shown in every layer.
=> Render railway positions for low zooms without decimal

import/openrailwaymap.lua, import/sql/tile_views.sql, martin/configuration.yml, proxy/js/styles.mjs
This requires a different rendering for polygons as for points, because the polygons need to have their center rendered for the lower zoom levels.
The center can only be calculated in the backend, not during rendering in MapLibre GL JS.
The center is stored along with the full geometry, such that polygon signal boxes can be rendered as such for high zoom levels.
The `signals_signal_boxes` tile source is converted to a function to ensure it can take the zoom level into account to determine which geometry to return to the client.
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/133
=> Render signal boxes as points with text below

features/signals_railway_signals.yaml
Fixes #155 
The signal type was wrongly configured.
Now it works
=> fix: signal type for DE-BOStrab:so5

features/signals_railway_signals.yaml
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/160
It was mistagged as Bü4
=> fix: crossing distant sign Bü 2 not rendered

proxy/css/ui.css, proxy/js/features.mjs, proxy/js/ui.js
Formatting of feature values:
- Voltage
- Frequency 
- Loading gauge feature lookup
- Train protection feature lookup
=> Formatting for feature properties

features/electrification_signals.yaml, features/signals_railway_signals.yaml
The tagging for ne5 was wrong, and the description for the Schaltzeiger was too close to the tag.
=> Improve tagging/description for ne5 and schaltzeiger

features/signals_railway_signals.yaml
Right now distant H/V signals take higher priority over their main counterparts, causing main signals with a distant signal attached to be drawn as distant signal, which is wrong, as the main signal is more important.
Example now https://openrailwaymap.fly.dev/#view=16.48/49.470724/10.991369&style=signals
With this fix all signals with a main signal ref, e.g. (N|P|S|R)[1-9]+ are drawn correctly. This matches the old ORM style:
=> Draw distant H/V signals with lower priority than main signals 

tiles/tiles.sh
merging the 8-9 and 10+ zoom tiles outputs a minzoom of 10, hiding all railway lines on zoom 8 up to 10:
=> fix high railway tiles only available from zoom 10

proxy/js/styles.mjs
Since https://github.com/hiddewie/OpenRailwayMap-vector/pull/197
`way_length` is now in meters instead of degrees.
With this change, bridges of short length in the current zoom level are not shown with casing:
=> Fix `way_length` using meter unit for showing bridges

proxy/proxy.conf.template
This shows outdated tiles even when they have been updated. Another refresh shows the updated tiles.
=> Do not use stale cache while revalidating

proxy/js/styles.mjs
Situation right now, when rotating the map
Afterward
=> Don't rotate signal direction indicators

proxy/js/styles.mjs
This sets minzoom for signals on this layer to the same value as on the speed and train protection layers.
=> Set minzoom for electrification signals to 13

features/signals_railway_signals.yaml
Due to change in Belgian railway tagging scheme, I propose to adapt the tags `railway:signal:minor=BE:SAS` and `railway:signal:shunting=BE:PSA`.
=> BE:SAS becomes minor signal, BE:PSA becomes shunting signal

proxy/js/ui.js
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/244
The full screen control, https://github.com/maplibre/maplibre-gl-js/blob/b52cb12b19b1064741bf821683c93e823d50294b/src/ui/control/fullscreen_control.ts#L52 uses the `requestFullscreen()` browser function (see https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen).
This puts a single element (the map) full screen, instead of the entire page. Especially the popup dialogs, and the background maps, are separate components on the screen, so not included in the full screen component of just the map.
Solution: remove the full-screen button alltogether.
It remains possible to put the browser in full screen mode by using the `F11` button (or the browser menu controls).
=> fix: remove full screen map button

import/openrailwaymap.lua
Completely untested...
I noted that non-electrified tracks and also tracks without electrification tags are rendered in gray while black is already defined in `styles.mjs`. This might fix it.
=> handle electrified=no vs. unknown electrification

.github/workflows/test.yml
See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull-request-events-for-forked-repositories
Ref https://github.com/hiddewie/OpenRailwayMap-vector/pull/232#issuecomment-2666803060
This PR should solve the problem that there is no button to approve CI to run the tests on pull requests from forked repositories.
=> Run tests on pull requests from forked repositories

proxy/js/features.mjs
From discussion with #278
The station size is good for showing stations at certain zoom levels, but there the value small / normal / large is rather arbitrary.
=> Stop showing station size in the popup

proxy/js/styles.mjs
Fixes #277
Light mode:
Dark mode:
Hover on locally operated switch (dark mode):
=> Fix colorings of locally operated switches in dark mode

import/openrailwaymap.lua
Fixes #192
Ignore maxspeed tags for razed/abandoned railways
Way https://www.openstreetmap.org/way/35361564
On http://localhost:8000/#view=13.71/45.61507/-72.98418&style=standard
Speed layer does not show razed/abandoned railways:
=> Do not render maxspeed for razed/abandoned railways

import/openrailwaymap.lua
From comment https://github.com/hiddewie/OpenRailwayMap-vector/pull/300#issuecomment-2750964599. 
Change `railway:resetting` to `railway:switch:resetting` in the import code.
See https://github.com/hiddewie/OpenRailwayMap-vector/pull/309
=> Fix tag for resetting switches

features/loading_gauge.yaml
Added EBV Loading gauges to OSM where publicly available (only BLS network) no rendering existed for 3/4 of them,
=> Add missing EBV (Swiss) loading gauges

proxy/js/ui.js
Currently, when the map is rotated, the background map is not rotated in the same way when the page loads.
Parsing the bearing from the map view hash manually works.
=> Parse bearing on map load

proxy/js/ui.js
http://localhost:8000/#view=18.2/52.263192/10.598613/22.6&style=speed
> Lookup catalog openrailwaymap_speed-speed_railway_signals did not contain value de/lf6-sign-down-{120} for feature  ...
This is caused because the variable part `{120}` is not extracted correctly.
After:
=> Fix secondary/tertiary feature lookup for signals with variables

proxy/js/ui.js
The popup currently opens very close to the center point of the feature on the map.
The offsets can tweak this. See https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/PopupOptions/
Not perfect yet for stacked icons (e.g. multiple signals on single pole), but works well for most icons.
http://localhost:8000/#view=15.6/50.942202/6.964626/22.6&style=speed
=> Make popup not overlap with icons

proxy/proxy.conf.template
Limit: 10 req/sec per IP, with a burst of 50.
This should allow normal loading of the map, including quite some tiles.
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/323
Docs in https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
=> Rate limit requests

proxy/proxy.conf.template
From https://github.com/hiddewie/OpenRailwayMap-vector/pull/324
Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/323
Changes:
- `nodelay` option to allow bursts without delays
- split rate limiting between assets, API and tiles with different limits
=> Tweak rate limiting configuration

.github/workflows/nightly-update.yml, .github/workflows/test.yml
Currently running tests for forks fails because the packages in the `hiddewie` namespace are pushed. This does not work (no permissions). Try to encode the owner into the package namespace, so forks can push packages into their own namespace.
=> Run tests for forks

api/openrailwaymap_api/facility_api.py, api/test/api.hurl, import/sql/get_station_importance.sql
Changes:
- make `stations_with_route_count` a materialized view
- index the view by `id` for more efficient joining during building of `grouped_stations_with_route_count`
- add only distinct values in the aggregated station fields.
I thought this would not be needed: let Postgres use a full table scan with join in a temporary table to build `grouped_stations_with_route_count`, and then query the unnested `stations_clustered` for each station ID (that view is also materialized and indexed). But it does make a difference to have both views materialized and indexed.
Query plan for `CREATE MATERIALIZED VIEW IF NOT EXISTS grouped_stations_with_route_count` (Europe):
```
GroupAggregate  (cost=33344.86..59354.47 rows=105530 width=628) (actual time=160.622..2050.760 rows=105530 loops=1)
Group …
```
=> Improve import speed for stations

proxy/js/styles.mjs
Render Resetting switches with a yellowish color for the icon.
http://localhost:8000//#view=17.61/49.179085/8.644021&style=standard
Also see https://github.com/OpenRailwayMap/OpenRailwayMap/issues/900
=> Resetting switches with custom icon color

proxy/js/ui.js
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/350
Problem: during map load, the historical style is configured, before the map is loaded or the date is changes. As such, there is no code that configures the historical style to put the configured date into the style layers.
Solution: if the historical view is active, configure the style to take the date filtering into account.
=> Fix date missing from historical layers when loading map

proxy/js/styles.mjs, proxy/js/ui.js
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/351
See default attribution control options in https://github.com/maplibre/maplibre-gl-js/blob/3a1f71f00913bf85d614d9693f5abcdd8f8bae8e/src/ui/control/attribution_control.ts
Problem: when only historical layers are shown, no attribution is provided to .
The background map layers do not provide any attribution to the shown layers / style. Ideally the background map layers would provide attribution to the main map. This is not feasible at the moment with two separate maps (one for the main OpenRailwayMap style and one for the background map style).
Solution: always provide attribution to OpenStreetMap, MapLibre and OpenRailwayMap.
Attribution to OpenHistoricalMap is added automatically when historical layers are shown.
=> Always provide OpenStreetMap attribution

.github/workflows/deploy-tiles.yml, .github/workflows/deploy.yml, docker-compose.yml, tiles/tiles.sh
From https://github.com/hiddewie/OpenRailwayMap-vector/issues/260#issuecomment-2713286861
The comment indicates that showing the freshness of the OSM data on OpenRailwayMap is useful.
The replication timestamp is stored in the Osmium metadata during download. of the OSM data. The Osmium metadata is imported into the properties table of Osm2psql. 
During tile generation the replication timestamp can be extracted and stored in the tile metadata.
Merging and conversion to PMTiles should keep tile metadata intact.
Then, it has to be shown in the UI.
=> Set replication timestamp in tile metadata

proxy/js/ui.js
Part of #260
On page load, the data source is queried for the replication timestamp. If it exists in the metadata, it shows the relative timestamp in the information balloon next to the data attribution.
Hover shows the full timestamp when the data was updated.
=> Show replication timestamp in the UI

features/signals_railway_signals.yaml
Extracted form https://github.com/hiddewie/OpenRailwayMap-vector/pull/369
Some signal types and tags were missing from the list.
=> Fix missing imported signal tags

features/signals_railway_signals.yaml
Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/269
Signals on mast from bottom to top:
- W1 
- W18
- W22
- W18
- W2/W26a/W26b
- W20/W19
- W24 
- W21
- Main / combined signals
W1 and route indicator below main signal
W18 below the main signal
http://localhost:8000/#view=16.62/52.213161/20.939129&style=signals
http://localhost:8000/#view=18.89/52.2090341/20.9242024&style=signals
=> Ordering of PL signals

features/signals_railway_signals.yaml
Fixes #269
On signal mast, from bottom to top:
- Shunting / minor signals
- Wrong road Zs 6
- Dead end Zs 13
- Distant Route direction Zs 2v
- Distant speed signals Zs 3v
- Distant signal Vr, Hl, Ks
- Main / combined signal
- Speed signal Zs 3
- Route direction Zs 2
The conditional placement of Zs 2 below the main/combined signal in case Zs 3 is present, is not implemented. 
Distant signals are below main signals
http://localhost:8000/#view=17.15/51.939655/7.633332&style=signals
Route signal on top, shunting on the bottom
http://localhost:8000/#view=18.79/51.9434865/7.6322188&style=signals
Wrong road, distant route and combined Ks signal
http://localhost:8000/#view=18.71/50.9496012/6.9523263&style=signals
Departure, distant, main and route signals …
=> Ordering of DE signals

import/sql/signal_features.sql.js
Problem: signals with two types (e.g. main and departure) are matched 2 times during import. This causes the same feature to be output twice for the same signal.
See e.g. https://openrailwaymap.fly.dev/#view=19.43/47.2588149/11.4025907&style=signals
After:
=> Fix duplicated signals if more than one type

proxy.Dockerfile, proxy/js/ui.js, proxy/proxy.conf.template, proxy/script/with-news-hash.sh, proxy/test/proxy.hurl
Currently the news hash changes too often, also on redeployment when the content of the news does not change.
Solution: calculate the news hash on startup using a SHA1, and expose a custom header `x-content-hash`.
First reload:
Reload, hash `68fe36f654263e549302c3317aaab0ad32c5ebc3` is picked up:
=> Set news hash explicitly

features/signals_railway_signals.yaml, symbols/de/bostrab/bü.svg, symbols/de/bostrab/bü2.svg, symbols/de/hha/sh3.svg
http://localhost:8000/#view=17/54.298121/13.088004&style=signals
See https://youtu.be/kEKcYJp7yzs?feature=shared&t=7185 and https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_in_Germany#Zs_6_ex-DR_Stumpfgleis-_und_Fr%C3%BChhaltanzeiger
http://localhost:8000/#view=16.38/49.647191/8.486991&style=signals
See https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_Trams_in_Germany#%C3%9Cberwachungssignale_f%C3%BCr_Bahn%C3%BCberg%C3%A4nge_(B%C3%BC)
http://localhost:8000/#view=16.8/53.547396/9.987211&style=signals
=> Missing DE signals

features/train_protection.yaml
From https://wiki.openstreetmap.org/w/index.php?title=OpenRailwayMap/Tagging&diff=next&oldid=2823775
http://localhost:8000/#view=9.32/48.7996/2.4718&style=signals
http://localhost:8000/#view=12.09/48.74155/2.27244&style=signals
http://localhost:8000/#view=14.77/48.71097/2.24001&style=signals
=> NEXTEO train protection

features/poi.yaml, import/sql/tile_views.sql, proxy/js/styles.mjs
Fixes #401 
The railway crossings, phones, subway entrances, buffer stops, derailer and retarders were not output in tiles.
The tiles are generated up to and including zoom level 14. Higher zoom levels are not output.
The standard POIs are now all output from zoom 14 and up. The map style is conditioned on zoom levels, showing just the features that need to be shown according to their minimum allowed zoom level.
Additionally, crossings are moved to zoom 15 instead of zoom 16.
=> Fix POIs with zoom levels > 14 not output to tiles

proxy/preset.py
Fixes #402
Vacancy detection already has a `railway` tag value, so does not need `railway=signal`.
=> Preset: fix duplicate tags for vacancy detection

proxy/js/features.mjs, proxy/js/styles.mjs
Fixes #408
Stations still work fine:
http://localhost:8000/#view=14.01/51.38781/-0.06701&date=1969
=> OpenHistoricalMap: use transport centroid points layer

.github/workflows/test.yml
The wrong files were cached.
e.g. https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/15511274470/job/43672557791
```
Post job cleanup.
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```
After, cache works:
https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/15511428649
=> Fix CI Berlin data cache

proxy.fly.toml
Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/431
Hosting the UI and tiles on Fly.io is getting expensive. Instead, let Cloudflare proxy and cache all assets and tiles. This should improve both latency, cache hit rates and data transfer.
There will be some graceful migration period were both openrailwaymap.fly.dev and openrailwaymap.app work, and after that a redirect.
Additionally: HTTP/3 support :)
=> Serve styles and tiles from `openrailwaymap.app` domain

features/train_protection.yaml
Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/448
=> Train protection: change *other* to *no train protection*

features/train_protection.yaml
See discussion in https://github.com/hiddewie/OpenRailwayMap-vector/discussions/449
https://openrailwaymap.app/#view=4.16/41.84/-94.04&style=signals
We could also change the coloring if that improves the differences or grouping between different train protection systems.
cc @DarkTrueNinja1 can you have a look if these changes makes sense?
Before:
After:
=> Ordering of north american train protection

import/openrailwaymap.lua, import/sql/api_facility_functions.sql, import/sql/api_facility_views.sql, import/sql/api_milestone_functions.sql, import/sql/api_milestone_views.sql, import/sql/update_api_views.sql
Followup on https://github.com/hiddewie/OpenRailwayMap-vector/pull/459
Simplify the database views because the API directly queries the database in the server deployment.
=> Simplify API database views

SETUP.md, compose.yaml
For local development.
```
docker compose up --build --watch api
```
watches the API directory to make the container automatically rebuild and restart after making changes.
=> Add watching to API container

import/openrailwaymap.lua, import/sql/get_station_importance.sql
Only platform nodes are used now for station area station <-> platform and station <-> stop position references. Platform ways should also work.
=> Station areas with platforms as ways

features/train_protection.yaml
Add ASES train protection. Separate entry, but same color as ACSES. Handles the `railway:ases = yes` tag.
From https://github.com/hiddewie/OpenRailwayMap-vector/pull/450#issuecomment-3037324103
=> ASES train protection

proxy/js/ui.js
When the map has a bearing on page load, the colored bearing map control did not show a color, even though it was rotated.
=> Fix map not showing colored rotation icon on page reload

import/openrailwaymap.lua
Followup on #481. A property was wrong, failing to import `mi:` and `pkm:` milestones.
=> Fix milestones wrong property during import

import/openrailwaymap.lua
Fixes #503
Import all switches, including those without a `ref`.
http://localhost:8000/#view=17.71/50.956407/7.012742
Before:
After:
=> Render switches without references

compose.yaml, proxy/js/styles.mjs, proxy/proxy.conf.template, proxy/test/proxy.hurl
Path rewriting for source URLs is no longer needed because everything runs in Docker with the same proxying rules. No tiles with different URLs.
=> Clean up source URLs

features/signals_railway_signals.yaml, taginfo.json
Fixes #520
See wiki about regime tagging on https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging_in_Belgium#Regime
Tested in Brussel (http://localhost:8000/#view=18.43/50.8245989/4.3233201&style=signals): icon is now inverted in opposite regime:
=> Use `railway:signal:regime` tag for BE signal regime

features/train_protection.yaml
ATMS ([enwiki](https://en.wikipedia.org/wiki/Advanced_Train_Management_System), [osmwiki](https://osm.wiki/Key:railway:atms)) is an Australian system, similar to ETCS but it uses GPS instead of Balises. 
Currently it's only used on [a single 74km line](https://en.wikipedia.org/wiki/Whyalla_railway_line), but it's being installed on [a 1600km line](https://en.wikipedia.org/wiki/Inland_Rail) now, and planned to be installed on [9600km of track](https://www.artc.com.au/about/network/) in the future
=> add ATMS to train_protection.yaml

deployment/filter-and-package-planet.sh
Otherwise permission errors might occur during linking with `cp`
=> Planet deployment script, plain copy

features/signals_railway_signals.yaml
Main/dwarf signals with shunting light add-on, and main signals with block marker add-on were not configured correctly.
(https://openrailwaymap.app/#view=15.6/51.859503/5.270863&style=signals)
Before:
After:
(https://openrailwaymap.app/#view=16/52.305968/6.932672&style=signals)
Before:
After:
=> Specify tagging for NL shunting / train protection signal addons

SETUP.md, compose.yaml, proxy/proxy.conf.template
Followup on #574.
Ref https://github.com/hiddewie/OpenRailwayMap-vector/issues/549#issuecomment-3351985508
Currently OpenRailwayMap is unreachable on https://openrailwaymap.app/ because Cloudflare proxies to port 443 and not to 8443.
=> Revert usage of port 8443

proxy/js/styles.mjs
For some reason the halo and hover of the signals became almost black. For the railway lines and text labels this is fine, but for the signals a more clear halo is nicer.
(http://localhost:8000/#view=17.22/48.629921/9.343935/-76.9&style=signals):
Before:
After:
=> Improve signal halo in dark mode
