hiddewie/OpenRailwayMap-vector

CONTRIBUTING.md
README.md

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/11

Expand contributing guidelines

---

proxy/css/ui.css
proxy/index.html
proxy/js/styles.mjs
proxy/js/ui.js

Show search results on map

---

.github/workflows/deploy.yml
api/api.fly.toml
api/start.sh
docker-compose.yml
proxy/proxy.conf.template

Fix IPv6 API host binding

---

import/openrailwaymap.lua
import/sql/tile_views.sql
martin/configuration.yml
proxy/js/ui.js

Adds reporting marks to the information pop-up
They are accessible to users to add to their custom style
https://wiki.openstreetmap.org/wiki/Key:reporting_marks

Reporting marks

---

CONTRIBUTING.md
features/train_protection.yaml
import/docker-startup.sh
import/openrailwaymap.lua

Fixes #55 
TODO:
---
Before:
After 
---
Paris
Ireland
Hungary and Romania
Belgium
Italy
Berlin
Moscow
Japan
Russia, Korea and China

Render missing train protection systems

---

api/Dockerfile
db/Dockerfile
import/openrailwaymap.lua
import/sql/functions.sql
import/sql/signals_with_azimuth.sql

See https://www.postgresql.org/about/news/postgresql-17-released-2936/
See https://hub.docker.com/layers/postgis/postgis/17-3.4-alpine/images/sha256-5a1dbedac34e0e6663f8b7190d393339571f1cb3ecb2ab2f724524b4f3c7956e?context=explore
The redefinition of a column with a function call no longer works in Postgres 17. 
The function call to determine the largest speed has been moved to Lua code.

Postgres 17

---

proxy/js/styles.mjs
proxy/js/ui.js

Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/60
This allows viewing symbols that are very close together a bit better.

Increase max zoom level to 20

---

features/signals_railway_signals.yaml
symbols/de/bostrab/sh4.svg

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/156
In Braunschweig:

feat: DE Tram läuten Sh 4 sign

---

features/train_protection.yaml

Part of https://github.com/hiddewie/OpenRailwayMap-vector/issues/154
Some of these are not tagged at all, or are not train protection systems.

feat: Remove untagged or invalid train protection systems

---

import/openrailwaymap.lua

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/157
Amsterdam Centraal:

fix: disused, abandoned, proposed and razed railway lines not imported

---

proxy/css/ui.css

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/175

fix: popup background color in dark mode

---

proxy/js/styles.mjs

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/181
Fixes train protection layer, loading gauge and track class preferred direction arrows and labels on track class railway lines.

fix color of direction arrows

---

proxy/js/features.mjs
proxy/js/ui.js

Fixes https://github.com/hiddewie/OpenRailwayMap-vector/issues/180

Fix empty popups for search results

---

features/electrification_signals.yaml
import/openrailwaymap.lua
import/sql/get_station_importance.sql
import/sql/signals_with_azimuth.sql.js
import/sql/tile_views.sql
martin/configuration.yml
proxy/js/features.mjs

Properties include:
- operator, traffic mode and radio for railway lines
- UIC ref for stations
- speed value for speed signals
- deactivated for speed and electricity signals
- voltage and frequency for electricity signals

Output more feature properties

---

proxy/js/ui.js

Solves https://github.com/hiddewie/OpenRailwayMap-vector/issues/173
Extracted from https://github.com/hiddewie/OpenRailwayMap-vector/pull/191.

Do not calculate diff when changing legend styles

---

api/Dockerfile
db/Dockerfile

See https://registry.hub.docker.com/layers/postgis/postgis/17-3.5-alpine/images/sha256-4580df07a4ecc6b3b4531d50900fbafdf978948f3f02fd5ccf1771fdf50e671a

Upgrade to PostGIS 3.5

---

features/signals_railway_signals.yaml
proxy/js/styles.mjs

Also remove some irrelevant TODOs

Fix broken icon for FI T-151A

---

proxy/js/styles.mjs

Fix constructed and proposed electrification rendering at low levels 

---

api/test/api.hurl

The order of Berlin stations changed in the OSM data.

Fix API tests (order of Berlin stations)

---

.github/workflows/test.yml

Followup on https://github.com/hiddewie/OpenRailwayMap-vector/pull/327 / https://github.com/hiddewie/OpenRailwayMap-vector/pull/328 which does not work
Instead, try https://docs.docker.com/build/ci/github-actions/share-image-jobs/ which uses plain .tar files as Github artifacts
Docs in https://docs.docker.com/reference/cli/docker/image/save/ and https://docs.docker.com/reference/cli/docker/image/load/

Run tests for forks (part 2)

---

features/train_protection.yaml

See e.g. https://www.openstreetmap.org/changeset/150508723 and https://www.irishrail.ie/en-ie/about-us/iarnrod-eireann-network-statement (https://www.irishrail.ie/getmedia/bf39f743-7194-444c-b34b-7980eee3f673/IE-2025-Network-Statement-(Final).pdf)

Track Circuit Block train protection (Ireland)

---

README.md
proxy/js/features.mjs
proxy/js/ui.js

Part of #246
The Railway lines do not have a `osm_id` property so linking does not work there.

Link to OpenHistoricalMap

---

SETUP.md
proxy/preset.py

Changes:
- icon for preset
- link for preset
- docs for locally fetching the preset zip

Preset improvements

---

.github/workflows/deploy-tiles.yml
.github/workflows/deploy.yml
.github/workflows/nightly-update.yml
.github/workflows/test.yml
api/Dockerfile
db/Dockerfile

For #313 
Goal: ensure that both AMD64 and ARM64 images build and run correctly.
See workflow run https://github.com/hiddewie/OpenRailwayMap-vector/actions/runs/14814434607 which runs successfully, including the screenshots.

Run tests on ARM64 runners

---

features/poi.yaml
import/openrailwaymap.lua
import/sql/get_station_importance.sql
martin/configuration.yml
proxy/js/features.mjs
proxy/js/styles.mjs
proxy/proxy.conf.template
tiles/tiles.sh

Fixes #419 
Reverts and improves https://github.com/hiddewie/OpenRailwayMap-vector/commit/46ba9938f6761418b0b9a05a3b87fce1e4f11c23
Brussel: http://localhost:8000/#view=14.6/50.85498/4.33865
Rotterdam: http://localhost:8000/#view=16.54/51.924782/4.46981

Display station area including subway entrances

---

tiles/tiles.sh

Reduces total tile size for zooms 10 to 12

Split signal tile generation

---

api/test/api.hurl

Berlin stations changed ordering again

Fix API tests

---

compose.yaml
proxy.Dockerfile
proxy/js/styles.mjs
proxy/js/ui.js

Split off from https://github.com/hiddewie/OpenRailwayMap-vector/pull/454
This makes the proxy image domain agnostic.

Support non-absolute URLs in style

---

proxy/css/ui.css
proxy/js/ui.js

Show compass color

---

deployment/README.md
deployment/download-planet.sh
deployment/filter-and-package-planet.sh
import/docker-startup.sh

Part of #513
Document and automate the downloading and publishing of filtered OSM planet data.

Document downloading, filtering and publishing the planet data

---

proxy/test/ui/package-lock.json
proxy/test/ui/package.json

This will hopefully fix the Cypress UI tests (ARM)

Upgrade Cypress to version 15
